import fs from 'fs';
import path from 'path';

const EXPERT_ARTICLES_PATH = path.join(process.cwd(), 'prisma', 'data', 'expert-articles.json');

/**
 * Formats HTML content to ensure professional typography, 
 * word wrapping, and bilingual support.
 */
export function formatRichText(content: string): string {
  if (!content) return '';

  let formatted = content;

  // 1. Remove empty paragraphs and redundant breaks often generated by editors
  formatted = formatted.replace(/<p><br><\/p>/g, '');
  
  // 2. Ensure paragraphs and headings have proper spacing and direction
  // We don't inject dir="auto" into every tag to avoid bloating, 
  // but we can ensure standard tags don't have breaking styles
  formatted = formatted.replace(/<p>/g, '<p dir="auto">');
  formatted = formatted.replace(/<h([1-6])>/g, '<h$1 dir="auto">');
  formatted = formatted.replace(/<li>/g, '<li dir="auto">');

  // 3. Clean up common messy inline styles that might come from copy-pasting
  // but keep basic formatting like colors or bold
  formatted = formatted.replace(/style="[^"]*word-break:[^;"]*;?[^"]*"/g, (match) => {
    return match.replace(/word-break:[^;"]*;?/g, '');
  });

  // 4. Ensure links open in new tabs for professional feel
  formatted = formatted.replace(/<a /g, '<a target="_blank" rel="noopener noreferrer" ');

  return formatted;
}

export interface ArticleData {
  slug: string;
  title?: string;
  [key: string]: unknown;
}

export async function syncArticleToSeeder(articleData: ArticleData) {
  try {
    // Ensure directory exists
    const dir = path.dirname(EXPERT_ARTICLES_PATH);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    let articles: ArticleData[] = [];
    if (fs.existsSync(EXPERT_ARTICLES_PATH)) {
      const fileContent = fs.readFileSync(EXPERT_ARTICLES_PATH, 'utf-8');
      articles = JSON.parse(fileContent);
    }

    // Check if article already exists by slug
    const index = articles.findIndex((a) => a.slug === articleData.slug);

    if (index !== -1) {
      // Update existing article
      articles[index] = { ...articles[index], ...articleData };
    } else {
      // Add new article
      articles.push(articleData);
    }

    // Write back to file
    fs.writeFileSync(EXPERT_ARTICLES_PATH, JSON.stringify(articles, null, 2), 'utf-8');
    console.log(`Successfully synced article "${articleData.title}" to seeder data.`);
  } catch (error) {
    console.error('Failed to sync article to seeder:', error);
    // We don't throw here to avoid failing the main action if seeder sync fails
  }
}

export async function removeArticleFromSeeder(slug: string) {
  try {
    if (!fs.existsSync(EXPERT_ARTICLES_PATH)) return;

    const fileContent = fs.readFileSync(EXPERT_ARTICLES_PATH, 'utf-8');
    let articles: ArticleData[] = JSON.parse(fileContent);

    articles = articles.filter((a) => a.slug !== slug);

    fs.writeFileSync(EXPERT_ARTICLES_PATH, JSON.stringify(articles, null, 2), 'utf-8');
    console.log(`Successfully removed article with slug "${slug}" from seeder data.`);
  } catch (error) {
    console.error('Failed to remove article from seeder:', error);
  }
}
